move wait out

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -130,16 +130,16 @@ push_tags() {
       local backgrounded_pid=$!
       push_tasks[${backgrounded_pid}]="${region}-${image}:${tag}"
     done
-    # Wait for completion
-    for pid in "${!push_tasks[@]}"; do
-      if wait "$pid"; then
-        echo "[${push_tasks[${pid}]}] Push task succeeded"
-        unset push_tasks[${pid}]
-      else
-        echo "[${push_tasks[${pid}]}] Push task failed"
-        exit 1
-      fi
-    done
+  done
+  # Wait for completion
+  for pid in "${!push_tasks[@]}"; do
+    if wait "$pid"; then
+      echo "[${push_tasks[${pid}]}] Push task succeeded"
+      unset push_tasks["${pid}"]
+    else
+      echo "[${push_tasks[${pid}]}] Push task failed"
+      exit 1
+    fi
   done
 }
 
